### ISSUE TITLE
Build Server [Jenkins]

### ISSUE THREAD

**Issue by bushshrub** [PseudoResonance/WolfAPI#3]
Can I auto-build this on Jenkins?
[https://ci-xiurobert.rhcloud.com] on Silver Gear (OpenShift)

I'll give you access to create an account on my build server

Besides that, you should really badge your repo with this. (Add it to your README)
`
[![Build Status](https://ci-xiurobert.rhcloud.com:443/buildStatus/icon?job=WolfAPI-Github)](https://ci-xiurobert.rhcloud.com:443/job/WolfAPI-Github/)
`

**Comment by xiurobert** [comment]
[https://ci-xiurobert.rhcloud.com] on Bronze Gear (OpenShift)

**Comment by xiurobert** [comment]
I'll give you access to the build server

**Comment by bushshrub** [comment]
Forget it. My build server crashed
